import type { NextPage } from "next";
import Head from "next/head";
import AboutSection from "src/components/home/aboutSection/aboutSection.component";
import CTASection from "src/components/home/ctaSection/ctaSection.component";
import HeroSection from "src/components/home/heroSection/heroSection.component";
import TestimonialComponent from "src/components/home/testimonialSection/testimonialSection.component";

const Home: NextPage = () => {
  return (
    <div className="px-8 max-">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />

      <div className="pb-14">
        <AboutSection />
      </div>

      <div className="py-14">
        <TestimonialComponent />
      </div>

      <div className="pb-14">
        <AboutSection />
      </div>

      <div className="py-14">
        <CTASection />
      </div>
    </div>
  );
};

export default Home;
